# https://docs.docker.com/reference/compose-file/services/#examples


services:
  ros_noetic_dev:
    build: . # build using the Dockerfile in the current directory
    stdin_open: true 
    tty: true
    volumes:
      # local src to container target. if it doesn't exist in the container already, Docker will create it
      - .:/ros_ws 
    network_mode: "host" # container can now share host machine's network interface (for interacting with ROS messages) 